Iss04
Nanostring-Biostats/GeoDiff pull request #6
Opened 2021-10-11 23:31 UTC by yangleicq

Address bioconductor review comments

2021-10-14 17:59 UTC, zhiiiyang requested changes
In addition, could you run `devtools::document()` to re-generate the man files?

2021-10-14 17:59 UTC, zhiiiyang commented on DESCRIPTION
> -    NanoStringNCTools,
This line of change will cause an error in `devtools::check()`. 

```
> checking package dependencies ... ERROR
  Namespace dependency missing from DESCRIPTION Imports/Depends entries: 'NanoStringNCTools'
  
  See section 'The DESCRIPTION file' in the 'Writing R Extensions'
  manual.
```

2021-10-14 21:00 UTC, yangleicq commented on DESCRIPTION
> +            The application of these methods are demonstrated by example data analysis vignette.
done

2021-10-15 16:53 UTC, zhiiiyang commented
looks good!

2021-10-15 16:53 UTC, merged